### ISSUE TITLE
Forcing error

### ISSUE THREAD

**Issue by rguarascia** [naokirin/fakey-cognito#26]
Hello, apologizes if this is mentioned [here](https://github.com/naokirin/fakey-cognito#configurations) but I don't fully understand how to implement. 

My goal is to force an error on certain functions. For example, I would like to force a `UsernameExistException` (which is a real Cognito error) on `AdminCreateUser` but also have one that passed.

I am attempting to write tests for functions and I would like to handle both cases of Success + UsernameExistException statuses.

Is this possible? If so, do you mind showing an example? 

Thank you!

**Comment by naokirin** [comment]
@rguarascia 

Thank you for creating this issue.

It is indeed possible to force an error, such as a `UsernameExistException`, while request the AdminCreateUser function. 

First, create a config.yml and write the following.
```yaml
AdminCreateUser:
   error_type: "UsernameExistsException"
```

Then execute following for running fackey-cognito.
```
$ cargo run -- --config /path/to/config.yml
or
$ docker run --rm -p 8080:8080 -v /path/to/config.yml:/app/config.yml ghcr.io/naokirin/fakey-cognito:main --config ./config.yml
```

And then run following.
```
curl -X POST http://localhost:8080 -H 'Content-Type:application/x-amz-json-1.1' -H 'X-Amz-Target:AWSCognitoIdentityProviderService.AdminCreateUser' -d '{"Username ":"username","UserPoolId":"userpool_id"}'
```

By making a request like this, I get the following response.
```json
{"__type": "UsernameExistsException","message":"force response from config."}
```

I hope this helps!

Best regards.

**Comment by naokirin** [comment]
Considering no response for the past week, I will close this issue.

If you believe this issue is still requires further discussion, reopen it.
